// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8gSqljJ9yfP8cPWva07oD4bum2HI7Bg',
    appId: '1:588441379617:web:d221836ed446e4b4d3d460',
    messagingSenderId: '588441379617',
    projectId: 'serendipity-sri-lanka',
    authDomain: 'serendipity-sri-lanka.firebaseapp.com',
    storageBucket: 'serendipity-sri-lanka.firebasestorage.app',
    measurementId: 'G-KBB6TD07DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRKhyHyx_YrW44JGCW6IqJvffw7m87fA',
    appId: '1:588441379617:android:438e71103709828dd3d460',
    messagingSenderId: '588441379617',
    projectId: 'serendipity-sri-lanka',
    storageBucket: 'serendipity-sri-lanka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-00qosgZsQuVu-TzcD1FBAPPpKQIzCPU',
    appId: '1:588441379617:ios:b319ad987e05f60cd3d460',
    messagingSenderId: '588441379617',
    projectId: 'serendipity-sri-lanka',
    storageBucket: 'serendipity-sri-lanka.firebasestorage.app',
    iosClientId: '588441379617-ic62fs5ovgra56spenv24fbikbf1pmng.apps.googleusercontent.com',
    iosBundleId: 'com.example.sriLankaTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-00qosgZsQuVu-TzcD1FBAPPpKQIzCPU',
    appId: '1:588441379617:ios:b319ad987e05f60cd3d460',
    messagingSenderId: '588441379617',
    projectId: 'serendipity-sri-lanka',
    storageBucket: 'serendipity-sri-lanka.firebasestorage.app',
    iosClientId: '588441379617-ic62fs5ovgra56spenv24fbikbf1pmng.apps.googleusercontent.com',
    iosBundleId: 'com.example.sriLankaTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX8gSqljJ9yfP8cPWva07oD4bum2HI7Bg',
    appId: '1:588441379617:web:fae5a338dc1514bbd3d460',
    messagingSenderId: '588441379617',
    projectId: 'serendipity-sri-lanka',
    authDomain: 'serendipity-sri-lanka.firebaseapp.com',
    storageBucket: 'serendipity-sri-lanka.firebasestorage.app',
    measurementId: 'G-SF43P43GVD',
  );

}